language: node_js

brances:
    only:
        - master

sudo: true

node_js:
    - "0.12"
    - "iojs"

services:
    - mongodb

notifications:
    email:
        on_success: never
        on_failure: never
